### ISSUE TITLE
知乎项目还是报错

### ISSUE THREAD

**Issue by yyyzzz674** [LinStan/VueStudy#2]
在浏览器中运行时，首页中没有数据，好像是axios设置有问题

**Comment by yyyzzz674** [comment]
在请求时，报       GET http://127.0.0.1:8010/news/before/20190315 net::ERR_CONNECTION_REFUSED

**Comment by yyyzzz674** [comment]
有时间的话，麻烦看一下

**Comment by LinStan** [comment]
你没有跑request的服务吧？
你先运行
node .\proxy.js

**Comment by yyyzzz674** [comment]
还真的是，没仔细看书，谢谢了
